added localized navmesh ft
Walled-City-Studio/Programming-Research pull request #1
Opened 2020-11-06 08:03 UTC by RickRietveld

2020-11-06 10:16 UTC, SeanSnel requested changes
Niet volledig volgens de style guide. De inhoud is echter wel goed!

2020-11-06 10:16 UTC, SeanSnel commented on navmesh-localized/Assets/Scripts/ClickToMove.cs
> +                agent.destination = hitInfo.point;
Hier moeten brackets omheen, zoals aangegeven wordt in de style guide

2020-11-06 10:16 UTC, SeanSnel commented on navmesh-localized/Assets/Editor/NavMeshPrefabInstanceEditor.cs
> +            return;
Hier moeten brackets, zoals aangegeven in de style guide.

2020-11-06 10:16 UTC, SeanSnel commented on navmesh-localized/Assets/Editor/NavMeshPrefabInstanceEditor.cs
> +            OnBake();
idem.

2020-11-06 10:16 UTC, SeanSnel commented on navmesh-localized/Assets/Editor/NavMeshPrefabInstanceEditor.cs
> +                DestroyImmediate(o, true);
idem.

2020-11-06 10:16 UTC, SeanSnel commented on navmesh-localized/Assets/Editor/NavMeshPrefabInstanceEditor.cs
> +            instance.UpdateInstance();
idem.

2020-11-06 10:16 UTC, SeanSnel commented on navmesh-localized/Assets/Scripts/LocalNavMeshBuilder.cs
> +            tracked = transform;
idem.

2020-11-06 10:16 UTC, SeanSnel commented on navmesh-localized/Assets/Scripts/LocalNavMeshBuilder.cs
> +            NavMeshBuilder.UpdateNavMeshData(navMesh, defaultBuildSettings, sources, bounds);
idem.

2020-11-06 10:16 UTC, SeanSnel commented on navmesh-localized/Assets/Scripts/NavMeshPrefabInstance.cs
> +            AddTracking();
idem.

2020-11-06 10:16 UTC, SeanSnel commented on navmesh-localized/Assets/Scripts/NavMeshPrefabInstance.cs
> +            instance = NavMesh.AddNavMeshData(navMesh, transform.position, transform.rotation);
idem

2020-11-06 10:16 UTC, SeanSnel commented on navmesh-localized/Assets/Scripts/NavMeshPrefabInstance.cs
> +            return;
idem.

2020-11-06 10:36 UTC, SeanSnel commented
![](https://github.trello.services/images/mini-trello-icon.png) [NPC pathfinding](https://trello.com/c/f0fQaJzy/2-npc-pathfinding)

2020-11-06 11:46 UTC, SeanSnel approved these changes, later dismissed
Ziet er goed uit!

2020-11-06 15:13 UTC, marthijn13 requested changes

2020-11-06 15:13 UTC, marthijn13 commented on navmesh-localized/Assets/Editor/NavMeshPrefabInstanceEditor.cs
> +        var go = instance.gameObject;
You are getting an instanced gameobject, why use var?

2020-11-06 15:13 UTC, marthijn13 commented on navmesh-localized/Assets/Editor/NavMeshPrefabInstanceEditor.cs
> +            var go = instance.gameObject;
You are getting an instanced gameobject, why use var?

2020-11-06 15:13 UTC, marthijn13 commented on navmesh-localized/Assets/Scripts/ClickToMove.cs
> +            var ray = Camera.main.ScreenPointToRay(Input.mousePosition);
var

2020-11-06 15:13 UTC, marthijn13 commented on navmesh-localized/Assets/Scripts/LocalNavMeshBuilder.cs
> +    private Vector3 size = new Vector3(80.0f, 20.0f, 80.0f);
Magic numbers, can these be placed in variables and serialized so they are easily changable?

2020-11-06 15:14 UTC, marthijn13 commented
A lot of vars that dont need to be there

2020-11-09 08:47 UTC, RickRietveld commented on navmesh-localized/Assets/Scripts/LocalNavMeshBuilder.cs
> +    private Vector3 size = new Vector3(80.0f, 20.0f, 80.0f);
These numbers are editable in the inspector -> (size is serialized)

2020-11-09 14:47 UTC, SeanSnel approved these changes

2020-11-10 10:40 UTC, marthijn13 approved these changes

2020-11-10 10:40 UTC, merged