Feature/quest system
Walled-City-Studio/Programming-Research pull request #7
Opened 2020-11-10 11:03 UTC by BBrendeke

2020-11-10 11:03 UTC, BBrendeke commented
![](https://github.trello.services/images/mini-trello-icon.png) [Quest system](https://trello.com/c/TXFM6ud7/9-quest-system)

2020-11-10 15:55 UTC, beumerr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Pakketten](https://trello.com/c/pgjBq8me/17-pakketten)

2020-11-10 15:55 UTC, beumerr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Pakketten](https://trello.com/c/pgjBq8me/17-pakketten)

2020-11-11 09:14 UTC, FrankvanKan requested changes

2020-11-11 09:14 UTC, FrankvanKan commented on Dialogue-system-research/Assets/Scripts/Dialogue.cs
> +    public string SentenceText;
Als dit een field blijft moet het met camelCase. Of je kan hier een property van maken met Getter en Setter.

2020-11-11 09:14 UTC, FrankvanKan commented on Dialogue-system-research/Assets/Scripts/DialogueTrigger.cs
> +}
Ik weet niet precies hoe jullie code in elkaar zit. Maar ik neem aan dat ergens in een andere MonoBehaviour `GetComponent<DialogueTrigger>().TriggerDialogue()` word gedaan. Kan deze MonoBehaviour misschien eruit gesloopt worden en in die andere MonoBehaviour als UnityEvent ingebouwd worden?

2020-11-11 09:14 UTC, FrankvanKan commented on Quest System/Unity Demo/Assets/DialogueSystem/Assets/Scripts/Dialogue.cs
> +    public string SentenceText;
Weer fields met camelCase

2020-11-11 09:14 UTC, FrankvanKan commented on Quest System/Unity Demo/Assets/DialogueSystem/Assets/Scripts/DialogueTrigger.cs
> +}
Trigger kan weer mogelijk vervangen worden voor een UnityEvent

2020-11-11 09:14 UTC, FrankvanKan commented on Quest System/Unity Demo/Assets/QSystem/Assets/Scripts/GUI/QGUIInventory.cs
> +}
Komt hier nog iets of is dit dode code? Want dan kan het weg. Plaats er anders even een comment bij dat het voor in de toekomst is.

2020-11-11 09:14 UTC, FrankvanKan commented on Quest System/Unity Demo/Assets/QSystem/Assets/Scripts/GUI/QGUILog.cs
> +}
Ook hier: Komt er nog iets? Plaats eventueel een comment.

2020-11-11 09:14 UTC, FrankvanKan commented on Quest System/Unity Demo/Assets/QSystem/Assets/Scripts/GUI/QGUIMap.cs
> +}
Plaats weer eventueel een comment als hier nog iets komt. Of verwijder het.

2020-11-11 09:14 UTC, FrankvanKan commented on Quest System/Unity Demo/Assets/QSystem/Assets/Scripts/GUI/QGUIOverlay.cs
> +        public Text QuestTotalTimeText;
camelCase voor fields

2020-11-11 09:14 UTC, FrankvanKan commented on Quest System/Unity Demo/Assets/QSystem/Assets/Scripts/QEnums.cs
> +}
Enum values doen we net als constants met: HOOFLETTERS, OF_ZO_MET_MEERDERE_WOORDEN

2020-11-11 09:14 UTC, FrankvanKan commented on Quest System/Unity Demo/Assets/QSystem/Assets/Scripts/QGiver.cs
> +        private SphereCollider SphereCollider;
Fields met camelCase. Attributes zetten we onder elkaar. In dit geval in de regel boven het bijbehorende field.

2020-11-11 09:14 UTC, FrankvanKan commented on Quest System/Unity Demo/Assets/QSystem/Assets/Scripts/QHandler.cs
> +        private int QuestMaxTime = 0;
Fields met camelCase

2020-11-11 09:14 UTC, FrankvanKan commented on Quest System/Unity Demo/Assets/QSystem/Assets/Scripts/QInventory.cs
> +		private List<QPackage> QPackages = new List<QPackage>();
camelCase

2020-11-11 09:14 UTC, FrankvanKan commented on Quest System/Unity Demo/Assets/QSystem/Assets/Scripts/QPickUpDelivery.cs
> +        private QPackage QPackage;
camelCase

2020-11-11 09:14 UTC, FrankvanKan commented on Quest System/Unity Demo/Assets/QSystem/Assets/Scripts/ScriptableObjects/QLocation.cs
> +    }
Fields met camelCase en Attributes boven de fields.

2020-11-11 09:14 UTC, FrankvanKan commented on Quest System/Unity Demo/Assets/QSystem/Assets/Scripts/ScriptableObjects/QPackage.cs
> +        public void OnEnable()
Fields met camelCase en Attributes boven de fields.

2020-11-11 09:14 UTC, FrankvanKan commented on Quest System/Unity Demo/Assets/QSystem/Assets/Scripts/ScriptableObjects/QReward.cs
> +
Fields met camelCase en Attributes boven de fields.

2020-11-11 09:14 UTC, FrankvanKan commented on Quest System/Unity Demo/Assets/QSystem/Assets/Scripts/ScriptableObjects/Quest.cs
> +    }
Fields met camelCase en Attributes boven de fields.

2020-11-11 10:33 UTC, FrankvanKan submitted a review, later dismissed

2020-11-11 10:53 UTC, FrankvanKan approved these changes, later dismissed

2020-11-11 12:42 UTC, marthijn13 requested changes

2020-11-11 12:42 UTC, marthijn13 commented on Quest System/Unity Demo/Assets/DialogueSystem/Assets/Scripts/DialogueManager.cs
> +            QSystem.QHandler.Instance.SetCurrentDiaglogueQuest();
Spell check

2020-11-11 12:42 UTC, marthijn13 commented on Quest System/Unity Demo/Assets/QSystem/Assets/Scripts/QInventory.cs
> +		}
Spellcheck

2020-11-11 12:42 UTC, marthijn13 commented on Quest System/Unity Demo/Assets/QSystem/Assets/Scripts/ScriptableObjects/QReward.cs
> +        public int ammount;
Spell check

2020-11-11 13:35 UTC, marthijn13 approved these changes

2020-11-11 13:52 UTC, FrankvanKan approved these changes

2020-11-11 14:01 UTC, merged